### ISSUE TITLE
Am I able to import this crate into my own Rust projects?

### ISSUE THREAD

**Issue by Joe23232** [MerosCrypto/meroxidizer#2]
Hi I am curious to know am I able to import this crate into my own Rust projects? I know it is technically possible to but how "user friendly" is it to use this as a crate with my own projects?

**Comment by kayabaNerve** [comment]
This has already been answered.

> The size of main + threads/mod.rs show this should be decently integrable. That said, this project isn't designed for that purpose and we have no plans to make it so at this time. It would be cool, as then we could build it into a Meros wallet, yet we currently don't have a Meros wallet in Rust to integrate it into.

Please don't open discussions via GitHub issues. It's a misuse of the system. We have community channels available for questions/comments.

**Comment by Joe23232** [comment]
Sorry about that and thank you.

**Comment by Joe23232** [comment]
@kayabaNerve Hey sorry what communities are you guys on?

**Comment by kayabaNerve** [comment]
We have a Discord. https://discord.meroscrypto.io
